import { useEffect, useMemo, useState } from 'react'

const API='http://localhost:4000/api'
const seedProjects=[{id:1,title:'NOVA HOUSE',type:'Hospitality',year:'2026',status:'Published'},{id:2,title:'MONO FORM',type:'Architecture',year:'2026',status:'Published'},{id:3,title:'ORBITAL',type:'Technology',year:'2025',status:'Draft'},{id:4,title:'SORA',type:'Lifestyle',year:'2025',status:'Published'}]
const seedServices=[{id:1,title:'Digital Strategy',text:'Turn ambitious ideas into clear digital direction.',enabled:true},{id:2,title:'Brand Systems',text:'Build a visual language people remember instantly.',enabled:true},{id:3,title:'Interactive Web',text:'Create responsive experiences that react to people.',enabled:true}]
export default function AdminPanel({onExit}){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('atelier-admin')==='1'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[active,setActive]=useState('Overview'),[projects,setProjects]=useState([]),[services,setServices]=useState([]),[inquiries,setInquiries]=useState([]),[notice,setNotice]=useState(''),[apiOnline,setApiOnline]=useState(false)
 const toast=m=>{setNotice(m);setTimeout(()=>setNotice(''),1800)}
 async function load(){try{const [p,s,i,h]=await Promise.all([fetch(`${API}/projects`),fetch(`${API}/services`),fetch(`${API}/inquiries`),fetch(`${API}/health`)]);if(!p.ok||!s.ok||!i.ok)throw Error();setProjects(await p.json());setServices(await s.json());setInquiries(await i.json());setApiOnline((await h.json()).ok)}catch{setApiOnline(false);setProjects(seedProjects);setServices(seedServices);setInquiries([])}}
 useEffect(()=>{if(loggedIn)load()},[loggedIn])
 const published=useMemo(()=>projects.filter(p=>p.status==='Published').length,[projects])
 const login=e=>{e.preventDefault();sessionStorage.setItem('atelier-admin','1');setLoggedIn(true)}
 const logout=()=>{sessionStorage.removeItem('atelier-admin');setLoggedIn(false)}
 async function addProject(){try{const r=await fetch(`${API}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`NEW PROJECT ${projects.length+1}`,type:'New category',year:'2026',status:'Draft'})});if(!r.ok)throw Error();setProjects(x=>[...x,await r.json()]);toast('Project created')}catch{toast('Start the backend first')}}
 async function toggleProject(p){try{const r=await fetch(`${API}/projects/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:p.status==='Published'?'Draft':'Published'})});if(!r.ok)throw Error();const u=await r.json();setProjects(x=>x.map(v=>v.id===p.id?u:v));toast('Status updated')}catch{toast('Backend unavailable')}}
 async function deleteProject(p){if(!confirm(`Delete ${p.title}?`))return;try{const r=await fetch(`${API}/projects/${p.id}`,{method:'DELETE'});if(!r.ok)throw Error();setProjects(x=>x.filter(v=>v.id!==p.id));toast('Project deleted')}catch{toast('Backend unavailable')}}
 async function clearInquiries(){try{const r=await fetch(`${API}/inquiries`,{method:'DELETE'});if(!r.ok)throw Error();setInquiries([]);toast('Inquiries cleared')}catch{toast('Backend unavailable')}}
 if(!loggedIn)return <main className="admin-login"><button className="back-site" onClick={onExit}>← Back to website</button><div className="login-card"><span className="brand-mark">A</span><p className="section-index">ADMIN ACCESS</p><h1>Control<br/><em>everything.</em></h1><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@atelier.studio" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label><button className="login-btn">Enter dashboard ↗</button></form><small>Demo mode · Any valid email and password</small></div></main>
 return <main className="admin-shell"><aside className="admin-sidebar"><button className="admin-logo" onClick={onExit}>A<span>.</span></button><p className="admin-label">CONTROL PANEL</p><nav>{['Overview','Projects','Services','Inquiries','Settings'].map(x=><button key={x} className={active===x?'admin-active':''} onClick={()=>setActive(x)}>{x}<span>↗</span></button>)}</nav><button className="exit-admin" onClick={onExit}>↗ View website</button></aside><section className="admin-content"><header className="admin-top"><div><p className="section-index">ADMIN · 2026</p><h2>{active==='Overview'?'Good to see you.':active}</h2></div><div className="admin-user"><span className="status-dot"/> API {apiOnline?'ONLINE':'OFFLINE'} <button onClick={logout}>Log out</button></div></header>
 {(active==='Overview'||active==='Projects')&&<><div className="admin-grid"><article className="admin-stat"><span>Published projects</span><strong>{published}</strong></article><article className="admin-stat"><span>Total projects</span><strong>{projects.length}</strong></article><article className="admin-stat"><span>Inquiries</span><strong>{inquiries.length}</strong></article></div><div className="admin-table-head"><div><p className="section-index">CONTENT MANAGER</p><h3>{active==='Projects'?'All projects':'Recent projects'}</h3></div><button className="add-project" onClick={addProject}>+ Add project</button></div><ProjectTable projects={projects} toggle={toggleProject} remove={deleteProject}/></>}
 {active==='Services'&&<div className="admin-list"><p className="section-index">SERVICE MANAGER</p>{services.map(s=><div className="admin-service" key={s.id}><div><strong>{s.title}</strong><p>{s.text}</p></div><span className={s.enabled?'published':'draft'}>{s.enabled?'VISIBLE':'HIDDEN'}</span></div>)}</div>}
 {active==='Inquiries'&&<div className="admin-list"><p className="section-index">CONTACT</p><h3>Client inquiries</h3>{inquiries.length===0?<div className="empty-state">No inquiries yet.</div>:inquiries.map(i=><div className="inquiry" key={i.id}><strong>{i.name}</strong><span>{i.email}</span><p>{i.message}</p></div>)}{inquiries.length>0&&<button className="delete-btn" onClick={clearInquiries}>Clear all</button>}</div>}
 {active==='Settings'&&<div className="admin-list"><p className="section-index">SYSTEM</p><div className="settings-card"><h3>Client Demo System</h3><p>API: {apiOnline?'Connected':'Offline'}</p><p>Server: Express</p><p>Data: server/data.json</p><span>Backend-connected content management.</span></div></div>}
 {notice&&<div className="admin-toast">✓ {notice}</div>}</section></main>
}
function ProjectTable({projects,toggle,remove}){return <div className="admin-table"><div className="table-row table-head"><span>PROJECT</span><span>CATEGORY</span><span>STATUS</span><span>ACTION</span></div>{projects.map(p=><div className="table-row" key={p.id}><strong>{p.title}</strong><span>{p.type}</span><button className={p.status==='Published'?'published':'draft'} onClick={()=>toggle(p)}>{p.status}</button><button className="delete-btn" onClick={()=>remove(p)}>DELETE</button></div>)}</div>}
