import { useEffect, useMemo, useState } from 'react'
const API=import.meta.env.VITE_API_URL||'/api'
const seedProjects=[{id:1,title:'NOVA HOUSE',type:'Hospitality',year:'2026',status:'Published',description:'A cinematic hospitality experience built around space, light and movement.',image:''},{id:2,title:'MONO FORM',type:'Architecture',year:'2026',status:'Published',description:'A minimal digital identity for a modern architecture practice.',image:''},{id:3,title:'ORBITAL',type:'Technology',year:'2025',status:'Draft',description:'A bold interface system for the next generation of technology.',image:''},{id:4,title:'SORA',type:'Lifestyle',year:'2025',status:'Published',description:'A warm, expressive digital home for a lifestyle brand.',image:''}]
const seedServices=[{id:'strategy',title:'Digital Strategy',text:'Turn ambitious ideas into clear digital direction.',enabled:true},{id:'brand',title:'Brand Systems',text:'Build a visual language people remember instantly.',enabled:true},{id:'web',title:'Interactive Web',text:'Create responsive experiences that react to people.',enabled:true}]
const seedSettings={heroLine:'We make digital',heroWord:'different.',heroText:'Strategy, identity and interactive experiences for ambitious brands that refuse to blend in.'}
export default function AdminPanel({onExit}){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('atelier-admin')==='1'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[active,setActive]=useState('Overview'),[projects,setProjects]=useState([]),[services,setServices]=useState([]),[inquiries,setInquiries]=useState([]),[settings,setSettings]=useState(seedSettings),[notice,setNotice]=useState(''),[apiOnline,setApiOnline]=useState(false),[editing,setEditing]=useState(null)
 const toast=m=>{setNotice(m);setTimeout(()=>setNotice(''),1800)}
 async function load(){try{const [p,s,i,h,c]=await Promise.all([fetch(`${API}/projects`),fetch(`${API}/services`),fetch(`${API}/inquiries`),fetch(`${API}/health`),fetch(`${API}/settings`)]);if(!p.ok||!s.ok||!i.ok||!h.ok||!c.ok)throw Error();setProjects(await p.json());setServices(await s.json());setInquiries(await i.json());setApiOnline((await h.json()).ok);setSettings(await c.json())}catch{setApiOnline(false);setProjects(seedProjects);setServices(seedServices);setInquiries([]);setSettings(seedSettings)}}
 useEffect(()=>{if(loggedIn)load()},[loggedIn])
 const published=useMemo(()=>projects.filter(p=>p.status==='Published').length,[projects])
 const login=e=>{e.preventDefault();sessionStorage.setItem('atelier-admin','1');setLoggedIn(true)}
 const logout=()=>{sessionStorage.removeItem('atelier-admin');setLoggedIn(false)}
 async function addProject(){try{const r=await fetch(`${API}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`NEW PROJECT ${projects.length+1}`,type:'New category',year:'2026',status:'Draft',description:'Add your project story here.',image:''})});if(!r.ok)throw Error();const item=await r.json();setProjects(x=>[...x,item]);setEditing(item);toast('Project created')}catch{toast('Start the backend first')}}
 async function saveProject(){try{const r=await fetch(`${API}/projects/${editing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});if(!r.ok)throw Error();const item=await r.json();setProjects(x=>x.map(p=>String(p.id)===String(item.id)?item:p));setEditing(null);toast('Project saved')}catch{toast('Backend unavailable')}}
 async function toggleProject(p){try{const r=await fetch(`${API}/projects/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:p.status==='Published'?'Draft':'Published'})});if(!r.ok)throw Error();const u=await r.json();setProjects(x=>x.map(v=>String(v.id)===String(u.id)?u:v));toast('Status updated')}catch{toast('Backend unavailable')}}
 async function deleteProject(p){if(!confirm(`Delete ${p.title}?`))return;try{const r=await fetch(`${API}/projects/${p.id}`,{method:'DELETE'});if(!r.ok)throw Error();setProjects(x=>x.filter(v=>String(v.id)!==String(p.id)));toast('Project deleted')}catch{toast('Backend unavailable')}}
 async function toggleService(s){try{const r=await fetch(`${API}/services/${s.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!s.enabled})});if(!r.ok)throw Error();const u=await r.json();setServices(x=>x.map(v=>String(v.id)===String(u.id)?u:v));toast('Service updated')}catch{toast('Backend unavailable')}}
 async function saveSettings(){try{const r=await fetch(`${API}/settings`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});if(!r.ok)throw Error();setSettings(await r.json());toast('Website settings saved')}catch{toast('Backend unavailable')}}
 async function clearInquiries(){try{const r=await fetch(`${API}/inquiries`,{method:'DELETE'});if(!r.ok)throw Error();setInquiries([]);toast('Inquiries cleared')}catch{toast('Backend unavailable')}}
 if(!loggedIn)return <main className="admin-login"><button className="back-site" onClick={onExit}>← Back to website</button><div className="login-card"><span className="brand-mark">A</span><p className="section-index">ADMIN ACCESS</p><h1>Control<br/><em>everything.</em></h1><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@atelier.studio" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label><button className="login-btn">Enter dashboard ↗</button></form><small>Demo mode · Any valid email and password</small></div></main>
 return <main className="admin-shell"><aside className="admin-sidebar"><button className="admin-logo" onClick={onExit}>A<span>.</span></button><p className="admin-label">CONTROL PANEL</p><nav>{['Overview','Projects','Services','Inquiries','Settings'].map(x=><button key={x} className={active===x?'admin-active':''} onClick={()=>setActive(x)}>{x}<span>↗</span></button>)}</nav><button className="exit-admin" onClick={onExit}>↗ View website</button></aside><section className="admin-content"><header className="admin-top"><div><p className="section-index">ADMIN · 2026</p><h2>{active==='Overview'?'Good to see you.':active}</h2></div><div className="admin-user"><span className="status-dot"/> API {apiOnline?'ONLINE':'OFFLINE'} <button onClick={logout}>Log out</button></div></header>
 {(active==='Overview'||active==='Projects')&&<><div className="admin-grid"><article className="admin-stat"><span>Published projects</span><strong>{published}</strong></article><article className="admin-stat"><span>Total projects</span><strong>{projects.length}</strong></article><article className="admin-stat"><span>Inquiries</span><strong>{inquiries.length}</strong></article></div><div className="admin-table-head"><div><p className="section-index">CONTENT MANAGER</p><h3>{active==='Projects'?'All projects':'Recent projects'}</h3></div><button className="add-project" onClick={addProject}>+ Add project</button></div><ProjectTable projects={projects} toggle={toggleProject} remove={deleteProject} edit={setEditing}/></>}
 {active==='Services'&&<div className="admin-list"><p className="section-index">SERVICE MANAGER</p>{services.map(s=><div className="admin-service" key={s.id}><div><strong>{s.title}</strong><p>{s.text}</p></div><button className={s.enabled?'published':'draft'} onClick={()=>toggleService(s)}>{s.enabled?'VISIBLE':'HIDDEN'}</button></div>)}</div>}
 {active==='Inquiries'&&<div className="admin-list"><p className="section-index">CONTACT</p><h3>Client inquiries</h3>{inquiries.length===0?<div className="empty-state">No inquiries yet.</div>:inquiries.map(i=><div className="inquiry" key={i.id}><strong>{i.name}</strong><span>{i.email}</span><p>{i.message}</p><small>{new Date(i.createdAt).toLocaleString()}</small></div>)}{inquiries.length>0&&<button className="delete-btn" onClick={clearInquiries}>Clear all</button>}</div>}
 {active==='Settings'&&<div className="admin-list"><p className="section-index">WEBSITE EDITOR</p><h3>Hero content</h3><div className="settings-card"><label>Headline<input value={settings.heroLine} onChange={e=>setSettings({...settings,heroLine:e.target.value})}/></label><label>Animated word<input value={settings.heroWord} onChange={e=>setSettings({...settings,heroWord:e.target.value})}/></label><label>Description<textarea value={settings.heroText} onChange={e=>setSettings({...settings,heroText:e.target.value})}/></label><button className="add-project" onClick={saveSettings}>Save website ↗</button></div></div>}
 {editing&&<div className="editor-overlay"><div className="editor-card"><button className="editor-close" onClick={()=>setEditing(null)}>×</button><p className="section-index">PROJECT EDITOR</p><h3>{editing.title}</h3><label>Project name<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Category<input value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}/></label><label>Year<input value={editing.year} onChange={e=>setEditing({...editing,year:e.target.value})}/></label><label>Description<textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Image URL<input value={editing.image||''} onChange={e=>setEditing({...editing,image:e.target.value})} placeholder="https://.../image.jpg"/></label>{editing.image&&<img className="image-preview" src={editing.image} alt="Project preview" onError={e=>e.currentTarget.style.display='none'}/>}<div className="editor-actions"><button className="add-project" onClick={saveProject}>Save changes</button><button className="delete-btn" onClick={()=>setEditing(null)}>Cancel</button></div></div></div>}
 {notice&&<div className="admin-toast">✓ {notice}</div>}</section></main>
}
function ProjectTable({projects,toggle,remove,edit}){return <div className="admin-table"><div className="table-row table-head"><span>PROJECT</span><span>CATEGORY</span><span>STATUS</span><span>ACTION</span></div>{projects.map(p=><div className="table-row" key={p.id}><strong>{p.title}</strong><span>{p.type}</span><button className={p.status==='Published'?'published':'draft'} onClick={()=>toggle(p)}>{p.status}</button><div><button onClick={()=>edit({...p})}>EDIT</button><button className="delete-btn" onClick={()=>remove(p)}>DELETE</button></div></div>)}</div>}
